export const CHALLENGE_START_YEAR = 2010;
export const CHALLENGE_START_MONTH = 3; // +1
export const CHALLENGE_START_DAY = 10;
const CHALLENGE_START_HOURS = 3;
const CHALLENGE_START_MINUTES = 0;

export const CHALLENGE_END_YEAR = 2020;
export const CHALLENGE_END_MONTH = 4; // +1
export const CHALLENGE_END_DAY = 11;
const CHALLENGE_END_HOURS = 16;
const CHALLENGE_END_MINUTES = 0;

export const CHALLENGE_START_TIMESTAMP = new Date(
  CHALLENGE_START_YEAR,
  CHALLENGE_START_MONTH,
  CHALLENGE_START_DAY,
  CHALLENGE_START_HOURS,
  CHALLENGE_START_MINUTES,
).getTime();

export const CHALLENGE_END_TIMESTAMP = new Date(
  CHALLENGE_END_YEAR,
  CHALLENGE_END_MONTH,
  CHALLENGE_END_DAY,
  CHALLENGE_END_HOURS,
  CHALLENGE_END_MINUTES,
).getTime();

export const QUESTIONS_START_YEAR = 2010;
export const QUESTIONS_START_MONTH = 0; // +1
export const QUESTIONS_START_DAY = 10;
const QUESTIONS_START_HOURS = 3;
const QUESTIONS_START_MINUTES = 0;

export const QUESTIONS_END_YEAR = 2020;
export const QUESTIONS_END_MONTH = 4; // +1
export const QUESTIONS_END_DAY = 11;
const QUESTIONS_END_HOURS = 16;
const QUESTIONS_END_MINUTES = 0;

export const QUESTIONS_START_TIMESTAMP = new Date(
  QUESTIONS_START_YEAR,
  QUESTIONS_START_MONTH,
  QUESTIONS_START_DAY,
  QUESTIONS_START_HOURS,
  QUESTIONS_START_MINUTES,
).getTime();

export const QUESTIONS_END_TIMESTAMP = new Date(
  QUESTIONS_END_YEAR,
  QUESTIONS_END_MONTH,
  QUESTIONS_END_DAY,
  QUESTIONS_END_HOURS,
  QUESTIONS_END_MINUTES,
).getTime();

export const LEADERBOARD_UPDATING_END_YEAR = 2021;
export const LEADERBOARD_UPDATING_END_MONTH = 3; // +1
export const LEADERBOARD_UPDATING_END_DAY = 24;
export const LEADERBOARD_UPDATING_END_HOURS = 16;
export const LEADERBOARD_UPDATING_END_MINUTES = 0;

export const REGISTRATION_END_YEAR = 2020;
export const REGISTRATION_END_MONTH = 10; // +1
export const REGISTRATION_END_DAY = 24;
export const REGISTRATION_END_HOURS = 16;
export const REGISTRATION_END_MINUTES = 0;

export const QUESTION_TAGS = [];

export const USERS_BATCH_SIZE = 100;
export const USERS_PAGE_SIZE = 100;

export const QUESTIONS_BATCH_SIZE = 100;
export const QUESTIONS_PAGE_SIZE = 100;

export const LEADERBOARD_UPDATING_END_TIMESTAMP = new Date(
  LEADERBOARD_UPDATING_END_YEAR,
  LEADERBOARD_UPDATING_END_MONTH,
  LEADERBOARD_UPDATING_END_DAY,
  LEADERBOARD_UPDATING_END_HOURS,
  LEADERBOARD_UPDATING_END_MINUTES,
).getTime();

export const REGISTRATION_END_TIMESTAMP = new Date(
  REGISTRATION_END_YEAR,
  REGISTRATION_END_MONTH,
  REGISTRATION_END_DAY,
  REGISTRATION_END_HOURS,
  REGISTRATION_END_MINUTES,
).getTime();
